CREATE DATABASE IF NOT EXISTS campusfind;
USE campusfind;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(100) UNIQUE,
  password VARCHAR(255),
  studentNumber VARCHAR(50),
  lecturerId VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_name VARCHAR(100),
  device_id VARCHAR(50) UNIQUE,
  user_id INT,
  floor INT DEFAULT 0,
  x FLOAT DEFAULT 0.5,
  y FLOAT DEFAULT 0.5,
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);